### ISSUE TITLE
Don't fail if /sys/class/hidraw is missing

### ISSUE THREAD

**Issue by rgooch** [Symantec/keymaster#154]
On a Linux system, if /sys/class/hidraw is missing, the `keymaster` client fails. One has to use the `-noU2F` flag to make it work. This is frustrating.

**Comment by cviecco** [comment]
New PR added to try to fix this: [https://github.com/Symantec/keymaster/pull/201](https://github.com/Symantec/keymaster/pull/201)

**Comment by cviecco** [comment]
Fixed with merge of: [https://github.com/Symantec/keymaster/pull/201](https://github.com/Symantec/keymaster/pull/201)
